from fpdf import FPDF
import datetime
from PIL import Image
import io

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, 'Voltage Drop Report – BS 7671', ln=True, align='C')
        self.ln(10)

def generate_pdf(path, data, logo_file=None):
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    if logo_file:
        img = Image.open(logo_file)
        img_bytes = io.BytesIO()
        img.save(img_bytes, format="PNG")
        pdf.image(img_bytes, 10, 8, 30)

    pdf.cell(0, 10, f"Engineer: {data['engineer']}", ln=True)
    pdf.cell(0, 10, f"Job Number: {data['job_number']}", ln=True)
    pdf.cell(0, 10, f"Date: {datetime.date.today()}", ln=True)
    pdf.ln(10)

    for key, val in data.items():
        if key not in ["engineer", "job_number"]:
            pdf.cell(0, 10, f"{key.replace('_', ' ').title()}: {val}", ln=True)

    pdf.ln(10)
    pdf.cell(0, 10, "Report generated by Streamlit Voltage Drop App", ln=True, align='C')

    pdf.output(str(path))
