from fpdf import FPDF
import datetime
from PIL import Image
import io
import tempfile

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, 'Voltage Drop Report – BS 7671', ln=True, align='C')
        self.ln(10)

def generate_pdf(path, data, logo_file=None):
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # ✅ Handle optional logo (uploaded file)
    if logo_file is not None:
        try:
            img = Image.open(logo_file)
            temp_logo = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
            img.save(temp_logo.name, format="PNG")
            pdf.image(temp_logo.name, 10, 8, 30)
        except Exception as e:
            pdf.set_text_color(255, 0, 0)
            pdf.cell(0, 10, f"⚠️ Logo failed to load: {e}", ln=True)
            pdf.set_text_color(0, 0, 0)

    # Header info
    pdf.cell(0, 10, f"Engineer: {data.get('engineer', 'N/A')}", ln=True)
    pdf.cell(0, 10, f"Job Number: {data.get('job_number', 'N/A')}", ln=True)
    pdf.cell(0, 10, f"Date: {datetime.date.today()}", ln=True)
    pdf.ln(10)

    # Key results
    for key, val in data.items():
        if key not in ["engineer", "job_number"]:
            pdf.cell(0, 10, f"{key.replace('_', ' ').title()}: {val}", ln=True)

    pdf.ln(10)
    pdf.cell(0, 10, "Report generated by Voltage Drop Calculator", ln=True, align='C')

    pdf.output(str(path))
